name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: deneOS.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore solution (mejor que proyecto suelto)
    - name: Restore
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build deneFiles
    - name: Build deneFiles
      run: msbuild deneFiles/deneFiles.csproj /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build deneNavi
    - name: Build deneNavi
      run: msbuild deneNavi/deneNavi.csproj /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build deneNotes
    - name: Build deneNotes
      run: msbuild deneNotes/deneNotes.csproj /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
